-- create role
USE ROLE ACCOUNTADMIN;

-- create warehouse
CREATE OR REPLACE WAREHOUSE healthcare_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE healthcare_WH;

-- create database
CREATE OR REPLACE DATABASE HEALTH_DB;
USE DATABASE HEALTH_DB;

-- create schema
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA ANALYTICS;

USE SCHEMA RAW;
USE SCHEMA STAGING;
USE SCHEMA ANALYTICS;

-- create file format
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE;

-- create stage for dataload
CREATE OR REPLACE STAGE healthcare_stage
FILE_FORMAT = CSV_FILE_FORMAT;